
import {curator} from './curator-client.js?v=20261001i';
const endpoint='https://mahjewznwqvdgtdjtekc.supabase.co/functions/v1/gaia-catalog';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=x=>{try{const u=new URL(x);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
let catalog, originals=new Map(),drafts=new Map(),saving=false;
let localQuotes=[];try{localQuotes=JSON.parse(localStorage.getItem('gaia_quote_edits')||'[]')}catch{}
const list=document.querySelector('#list'),status=document.querySelector('#status'),save=document.querySelector('#save');
async function call(action,payload={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Salvataggio non riuscito');return d;}
function initial(t){const q=localQuotes.find(q=>q.title_id===t.id)||t.quote_override||null;return {id:t.id,revision:t.revision,name:t.name,category:t.category,release_year:t.release_year,dvd_cover_url:t.dvd_cover_url,active:t.active,quote_override:q,links:catalog.platforms.map(p=>{const l=catalog.links.find(l=>l.title_id===t.id&&l.platform_id===p.id);return {platform_id:p.id,url:l?.url||null,active:l?.active===true}})};}
function mark(){save.disabled=saving||!drafts.size;save.textContent=saving?'Salvataggio…':'Salva modifiche'+(drafts.size?' ('+drafts.size+' titoli)':'');document.querySelector('#dirty').textContent=drafts.size?drafts.size+' titoli con modifiche non salvate.':'Nessuna modifica da salvare.';}
function edit(id,fn){const d=structuredClone(drafts.get(id)||originals.get(id));fn(d);if(JSON.stringify(d)===JSON.stringify(originals.get(id)))drafts.delete(id);else drafts.set(id,d);mark();}
function render(){const q=document.querySelector('#search').value.toLocaleLowerCase('it'),f=document.querySelector('#filter').value;const rows=catalog.titles.filter(t=>{const d=drafts.get(t.id)||originals.get(t.id);return d.name.toLocaleLowerCase('it').includes(q)&&(f==='all'||f==='active'&&d.active||f==='archived'&&!d.active||f==='dirty'&&drafts.has(t.id)||f==='no-quote'&&!d.quote_override?.text);});
document.querySelector('#count').textContent=rows.length+' titoli mostrati · '+catalog.titles.length+' nel catalogo';
list.innerHTML=rows.map(t=>{const d=drafts.get(t.id)||originals.get(t.id),quote=d.quote_override||{},image=d.dvd_cover_url||t.custom_image_url||t.poster_url;return `<article class="catalog-card" data-id="${esc(t.id)}"><div class="catalog-cover">${safe(image)?`<img src="${esc(safe(image))}" alt="Copertina di ${esc(d.name)}" loading="lazy">`:''}<button type="button" data-covers>Cambia copertina</button><div class="candidates"></div></div><div><h2>${esc(d.name)}${d.active?'':' · Archiviato'}</h2><div class="fields"><label>Titolo<input name="name" maxlength="300" required value="${esc(d.name)}"></label><label>Categoria<select name="category"><option value="animation" ${d.category==='animation'?'selected':''}>Animazione</option><option value="film" ${d.category==='film'?'selected':''}>Film</option></select></label><label>Anno<input name="release_year" type="number" min="1800" max="2200" value="${esc(d.release_year)}"></label></div><label>Indirizzo copertina<input name="dvd_cover_url" type="url" placeholder="https://…" value="${esc(d.dvd_cover_url)}"></label><label>Citazione scelta<textarea name="quote-text" maxlength="500" placeholder="Nessuna citazione scelta">${esc(quote.text)}</textarea></label><div class="fields"><label>Personaggio<input name="quote-speaker" maxlength="100" value="${esc(quote.speaker)}"></label><label>Fonte della citazione<input name="quote-source" type="url" value="${esc(quote.source)}"></label></div><fieldset><legend>Piattaforme</legend>${catalog.platforms.map(p=>{const l=d.links.find(l=>l.platform_id===p.id),stored=catalog.links.find(l=>l.title_id===t.id&&l.platform_id===p.id);return `<div class="platform-row" data-platform="${esc(p.id)}"><label><input type="checkbox" name="platform-active" ${l.active?'checked':''}> ${esc(p.name)}</label><input name="platform-url" type="url" aria-label="Link ${esc(p.name)}" value="${esc(l.url)}" placeholder="Collegamento al titolo">${safe(l.url)?`<a href="${esc(safe(l.url))}" target="_blank" rel="noopener">Apri ↗</a>`:''}<small>Ultima verifica: ${stored?.last_verified_at?esc(new Date(stored.last_verified_at).toLocaleDateString('it-IT')):'da verificare'}</small></div>`}).join('')}</fieldset><button type="button" data-archive>${d.active?'Archivia titolo':'Ripristina titolo'}</button><p class="card-status" role="status"></p></div></article>`}).join('');}
list.addEventListener('input',e=>{const card=e.target.closest('[data-id]');if(!card)return;edit(card.dataset.id,d=>{const name=e.target.name;if(name==='release_year')d[name]=e.target.value===''?null:Number(e.target.value);else if(['name','category','dvd_cover_url'].includes(name))d[name]=e.target.value;else if(name.startsWith('quote-')){d.quote_override={...(d.quote_override||{}),title_id:d.id,reviewed:true,reviewed_at:new Date().toISOString()};d.quote_override[{ 'quote-text':'text','quote-speaker':'speaker','quote-source':'source'}[name]]=e.target.value;}else if(name.startsWith('platform-')){const l=d.links.find(l=>l.platform_id===e.target.closest('[data-platform]').dataset.platform);if(name==='platform-active')l.active=e.target.checked;else l.url=e.target.value;}});});
list.addEventListener('click',async e=>{const card=e.target.closest('[data-id]');if(!card||saving)return;const id=card.dataset.id,msg=card.querySelector('.card-status');if(e.target.closest('[data-archive]')){edit(id,d=>d.active=!d.active);render();return;}
const cover=e.target.closest('[data-cover-url]');if(cover){edit(id,d=>d.dvd_cover_url=cover.dataset.coverUrl);render();return;}
if(e.target.closest('[data-covers]')){e.target.disabled=true;msg.textContent='Cerco le copertine già raccolte…';try{const {candidates}=await curator('covers',{titleId:id});if(!card.isConnected)return;card.querySelector('.candidates').innerHTML=candidates.map((c,i)=>`<button type="button" data-cover-url="${esc(c.url)}" aria-label="Scegli copertina ${i+1}"><img src="${esc(safe(c.preview_url||c.url))}" alt="" loading="lazy"></button>`).join('');msg.textContent=candidates.length?'Scegli una copertina: sarà confermata con Salva modifiche.':'Nessuna alternativa già raccolta disponibile.';}catch(err){msg.textContent=err.message;}finally{if(card.isConnected)e.target.disabled=false;}}});
document.querySelector('#search').addEventListener('input',render);document.querySelector('#filter').addEventListener('change',render);
window.addEventListener('beforeunload',e=>{if(drafts.size){e.preventDefault();e.returnValue='';}});
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.target!=='_blank'&&drafts.size&&!confirm('Ci sono modifiche non salvate. Premi Annulla e poi Salva modifiche per conservarle. Vuoi uscire senza salvarle?'))e.preventDefault();});
save.addEventListener('click',async()=>{if(saving||!drafts.size)return;const changes=[...drafts.values()];for(const c of changes){if(!c.name.trim()||c.name.length>300){status.textContent='Controlla il titolo del film.';return;}if(c.release_year!==null&&(!Number.isInteger(c.release_year)||c.release_year<1800||c.release_year>2200)){status.textContent='Controlla gli anni inseriti.';return;}for(const url of [c.dvd_cover_url,c.quote_override?.source,...c.links.map(l=>l.url)])if(url&&!safe(url)){status.textContent='Uno degli indirizzi non è valido.';return;}}
saving=true;mark();list.inert=true;status.textContent='Salvataggio di tutte le modifiche…';let persisted=false;try{const result=await call('saveCatalog',{changes});persisted=true;
const quotes=changes.filter(c=>JSON.stringify(c.quote_override)!==JSON.stringify(originals.get(c.id).quote_override));if(quotes.length){let edits=[];try{edits=JSON.parse(localStorage.getItem('gaia_quote_edits')||'[]')}catch{};for(const c of quotes){edits=edits.filter(q=>q.title_id!==c.id);edits.push({...c.quote_override,title_id:c.id,text:c.quote_override?.text||''});}try{localStorage.setItem('gaia_quote_edits',JSON.stringify(edits));localQuotes=edits;}catch{}}
drafts.clear();status.textContent=result.saved+' titoli salvati. ';await load();status.textContent=result.saved+' titoli salvati.';}catch(err){status.textContent=persisted?'Modifiche salvate, ma aggiornamento della pagina non riuscito. Riapri il catalogo.':err.message+' Le modifiche restano in questa pagina: puoi riprovare.';}finally{saving=false;list.inert=false;mark();}});
async function load(){catalog=await call('catalogEditor');originals=new Map(catalog.titles.map(t=>[t.id,initial(t)]));render();mark();}
try{await load()}catch(err){status.textContent=err.message;save.disabled=true;}
