import {effectiveQuote,standardQuote} from './title-quotes.js?v=20261002editor';
const endpoint='https://mahjewznwqvdgtdjtekc.supabase.co/functions/v1/gaia-api';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,payload={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Salvataggio non riuscito');return d;}
let titles=[],overrides=[];
try { overrides=JSON.parse(localStorage.getItem('gaia_quote_edits')||'[]'); } catch { overrides=[]; }
const list=document.querySelector('#list'),count=document.querySelector('#count');
function render(){
 const query=document.querySelector('#search').value.toLocaleLowerCase('it'),filter=document.querySelector('#filter').value;
 const shown=titles.filter(t=>t.name.toLocaleLowerCase('it').includes(query)).filter(t=>filter==='all'||Boolean(effectiveQuote(t,overrides))===(filter==='quoted'));
 count.textContent=`${shown.length} titoli · ${titles.filter(t=>effectiveQuote(t,overrides)).length} con citazione`;
 list.innerHTML=shown.map(t=>{const q=effectiveQuote(t,overrides);return `<form class="quote-card" data-id="${esc(t.id)}"><h2>${esc(t.name)}</h2><p>${esc(t.release_year||'Anno da verificare')} · ${q?'Citazione scelta':'Frase standard'}</p><p class="quote-preview">${q?`«${esc(q.text)}»`:esc(standardQuote)}</p>${q?.source?`<a href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">Leggi la fonte ↗</a>`:''}<label>Citazione<textarea name="text" maxlength="500" placeholder="Lascia vuoto per la frase standard">${esc(q?.text||'')}</textarea></label><div class="quote-fields"><label>Personaggio (facoltativo)<input name="speaker" maxlength="100" value="${esc(q?.speaker||'')}"></label><label>Fonte (facoltativa)<input name="source" type="url" placeholder="https://…" value="${esc(q?.source||'')}"></label></div><button class="ghost-btn" type="submit">Salva</button><button class="ghost-btn" type="button" data-standard>Usa frase standard</button><span role="status"></span></form>`}).join('');
}
list.addEventListener('click',e=>{if(e.target.matches('[data-standard]')){const form=e.target.closest('form');for(const name of ['text','speaker','source'])form.elements[name].value='';form.querySelector('[role=status]').textContent='Premi Salva per confermare la frase standard.';}});
list.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,status=form.querySelector('[role=status]'),button=form.querySelector('[type=submit]');button.disabled=true;status.textContent='Salvataggio…';try{const quote={title_id:form.dataset.id,text:form.elements.text.value.trim(),speaker:form.elements.speaker.value.trim(),source:form.elements.source.value.trim()}; if(quote.source && new URL(quote.source).protocol!=='https:')throw Error('La fonte deve iniziare con https://');overrides=overrides.filter(q=>q.title_id!==quote.title_id).concat(quote);localStorage.setItem('gaia_quote_edits',JSON.stringify(overrides));form.querySelector('p').textContent=`${titles.find(t=>t.id===quote.title_id)?.release_year||'Anno da verificare'} · ${quote.text?'Citazione scelta':'Frase standard'}`; const oldLink=form.querySelector('a');if(oldLink)oldLink.remove();if(quote.source){const a=document.createElement('a');a.href=quote.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Leggi la fonte ↗';form.querySelector('.quote-preview').after(a);}form.querySelector('.quote-preview').textContent=quote.text?`«${quote.text}»`:standardQuote;status.textContent='Salvata in questo browser.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#search').addEventListener('input',render);document.querySelector('#filter').addEventListener('change',render);
try{const catalog=await call('catalog');titles=catalog.titles;render();}catch(error){count.textContent=error.message;}

document.querySelector('#export').addEventListener('click',()=>{const data=overrides.map(q=>({...q,name:titles.find(t=>t.id===q.title_id)?.name,year:titles.find(t=>t.id===q.title_id)?.release_year}));const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gaia-citazioni.json';a.click();URL.revokeObjectURL(url);});
