import {proposalsFor} from './quote-proposals.js?v=20261002review';
import {effectiveQuote,standardQuote} from './title-quotes.js?v=20261002editor';
const endpoint='https://mahjewznwqvdgtdjtekc.supabase.co/functions/v1/gaia-api';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,payload={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Salvataggio non riuscito');return d;}
let titles=[],overrides=[];
try { overrides=JSON.parse(localStorage.getItem('gaia_quote_edits')||'[]'); } catch { overrides=[]; }
const reviewed=id=>overrides.some(q=>String(q.title_id)===String(id)&&q.reviewed===true);
const list=document.querySelector('#list'),count=document.querySelector('#count');
function render(){
 const query=document.querySelector('#search').value.toLocaleLowerCase('it'),filter=document.querySelector('#filter').value;
 const shown=titles.filter(t=>t.name.toLocaleLowerCase('it').includes(query)).filter(t=>filter==='all'||(filter==='proposed'?proposalsFor(t).length>0:filter==='no-proposals'?proposalsFor(t).length===0:filter==='reviewed'?reviewed(t.id):filter==='unreviewed'?!reviewed(t.id):Boolean(effectiveQuote(t,overrides))===(filter==='quoted')));
 count.textContent=`${shown.length} titoli · ${titles.filter(t=>effectiveQuote(t,overrides)).length} con citazione · ${titles.filter(t=>reviewed(t.id)).length} revisionate`;
 list.innerHTML=shown.map(t=>{const q=effectiveQuote(t,overrides);const options=proposalsFor(t);const isReviewed=reviewed(t.id);return `<form class="quote-card" data-id="${esc(t.id)}"><h2>${esc(t.name)}</h2><p>${esc(t.release_year||'Anno da verificare')} · ${q?'Citazione scelta':'Frase standard'}${isReviewed?' · Revisionata ✓':''}</p><p class="quote-preview">${q?`«${esc(q.text)}»`:esc(standardQuote)}</p>${q?.source?`<a class="selected-quote-source" href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">Leggi la fonte ↗</a>`:''}${options.length?`<div class="quote-proposals"><p>${options.length} proposte · gli estratti rimandano alla frase completa nella fonte.</p>${options.map((o,i)=>`<div class="quote-option"><button type="button" data-proposal="${i}" aria-pressed="false">«${esc(o.text)}»<small>${esc(o.speaker)}${o.excerpt?' · Estratto':''}</small></button><a href="${esc(o.source)}" target="_blank" rel="noopener noreferrer">Fonte ↗</a></div>`).join('')}</div>`:''}<label>Citazione<textarea name="text" maxlength="500" placeholder="Lascia vuoto per la frase standard">${esc(q?.text||'')}</textarea></label><div class="quote-fields"><label>Personaggio (facoltativo)<input name="speaker" maxlength="100" value="${esc(q?.speaker||'')}"></label><label>Fonte (facoltativa)<input name="source" type="url" placeholder="https://…" value="${esc(q?.source||'')}"></label></div><label class="review-label"><input type="checkbox" name="reviewed" ${isReviewed?'checked':''}> Revisionata</label><button class="ghost-btn" type="submit">Salva</button><button class="ghost-btn" type="button" data-standard>Usa frase standard</button><span role="status"></span></form>`}).join('');
}
list.addEventListener('click',e=>{const proposal=e.target.closest('[data-proposal]');if(proposal){const form=proposal.closest('form');const t=titles.find(t=>String(t.id)===form.dataset.id);const q=proposalsFor(t)[Number(proposal.dataset.proposal)];for(const name of ['text','speaker','source'])form.elements[name].value=q[name]||'';form.elements.reviewed.checked=false;form.querySelectorAll('[data-proposal]').forEach(b=>b.setAttribute('aria-pressed',String(b===proposal)));form.querySelector('[role=status]').textContent='Premi Salva per usare questa citazione.';}if(e.target.matches('[data-standard]')){const form=e.target.closest('form');for(const name of ['text','speaker','source'])form.elements[name].value='';form.elements.reviewed.checked=false;form.querySelector('[role=status]').textContent='Premi Salva per confermare la frase standard.';}});
list.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,status=form.querySelector('[role=status]'),button=form.querySelector('[type=submit]');button.disabled=true;status.textContent='Salvataggio…';try{const quote={title_id:form.dataset.id,text:form.elements.text.value.trim(),speaker:form.elements.speaker.value.trim(),source:form.elements.source.value.trim(),reviewed:form.elements.reviewed.checked,reviewed_at:form.elements.reviewed.checked?new Date().toISOString():null}; if(quote.source && new URL(quote.source).protocol!=='https:')throw Error('La fonte deve iniziare con https://');overrides=overrides.filter(q=>q.title_id!==quote.title_id).concat(quote);localStorage.setItem('gaia_quote_edits',JSON.stringify(overrides));form.querySelector('p').textContent=`${titles.find(t=>t.id===quote.title_id)?.release_year||'Anno da verificare'} · ${quote.text?'Citazione scelta':'Frase standard'}${quote.reviewed?' · Revisionata ✓':''}`; const oldLink=form.querySelector('.selected-quote-source');if(oldLink)oldLink.remove();if(quote.source){const a=document.createElement('a');a.className='selected-quote-source';a.href=quote.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Leggi la fonte ↗';form.querySelector('.quote-preview').after(a);}form.querySelector('.quote-preview').textContent=quote.text?`«${quote.text}»`:standardQuote;status.textContent='Salvata in questo browser.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#search').addEventListener('input',render);document.querySelector('#filter').addEventListener('change',render);
try{const catalog=await call('catalog');titles=catalog.titles;render();}catch(error){count.textContent=error.message;}

document.querySelector('#export').addEventListener('click',()=>{const data=overrides.map(q=>({...q,name:titles.find(t=>t.id===q.title_id)?.name,year:titles.find(t=>t.id===q.title_id)?.release_year}));const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gaia-citazioni.json';a.click();URL.revokeObjectURL(url);});

list.addEventListener('input',e=>{if(['text','speaker','source'].includes(e.target.name)){const form=e.target.closest('form');form.elements.reviewed.checked=false;form.querySelector('[role=status]').textContent='Modificata: da revisionare nuovamente. Premi Salva.';}});
document.querySelector('#review-saved').addEventListener('click',()=>{const now=new Date().toISOString();overrides=overrides.map(q=>({...q,reviewed:true,reviewed_at:now}));localStorage.setItem('gaia_quote_edits',JSON.stringify(overrides));render();document.querySelector('#review-status').textContent=`${overrides.length} citazioni salvate segnate come revisionate.`;});
